### ISSUE TITLE
Wrong error message when sending a floating point instead of a integer on updating score

### ISSUE THREAD

**Issue by traysh** [topfreegames/podium#4]
PUT on route /l/clan-${ranking}/members/${id}/score with the following body:
`{ score: 14.5 }`

resulted in:
`{ success: false, reason: 'score is required' }`

making it harder to debug the problem.

If score is an integer, everything works as expected:
```
{
  publicID: '0cac9c2b-5f02-4aa9-9709-71736d7d1f30',
  rank: 1,
  score: 62,
  success: true
}
```

**Comment by cscatolini** [comment]
Same thing happens when a string is sent.
